# Ops Agent Config for Mori advisor metrics & host system metrics
metrics:
  receivers:
    hostmetrics:
      type: hostmetrics
    mori_prometheus:
      type: prometheus
      config:
        scrape_configs:
          - job_name: 'mori-advisor'
            scrape_interval: 60s
            metrics_path: /metrics
            static_configs:
              - targets: ['localhost:8968']
  service:
    pipelines:
      default_pipeline:
        receivers: [hostmetrics]
      mori_pipeline:
        receivers: [mori_prometheus]
